// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX2m1EwU7GRLakXed3Kg_CmQvLWLuGZQ4',
    appId: '1:30188463436:web:4b8cfb218ebeee81179be9',
    messagingSenderId: '30188463436',
    projectId: 'social-media-platform-34794',
    authDomain: 'social-media-platform-34794.firebaseapp.com',
    storageBucket: 'social-media-platform-34794.firebasestorage.app',
    measurementId: 'G-1BTRLLW93G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFCoTbKjtx67Bl7TCv7wNIkDgUvpjkWEU',
    appId: '1:30188463436:android:75d44dcf5034d695179be9',
    messagingSenderId: '30188463436',
    projectId: 'social-media-platform-34794',
    storageBucket: 'social-media-platform-34794.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA68cNnhQybiQVZG114IJBx4r7x_ZZxj9o',
    appId: '1:30188463436:ios:fe1c68aae7ca2741179be9',
    messagingSenderId: '30188463436',
    projectId: 'social-media-platform-34794',
    storageBucket: 'social-media-platform-34794.firebasestorage.app',
    androidClientId: '30188463436-9q44hre5h3ooods0erikpbkdqe446rjl.apps.googleusercontent.com',
    iosClientId: '30188463436-apk9rrf186g5i1bf1jdij9pjosup2n3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA68cNnhQybiQVZG114IJBx4r7x_ZZxj9o',
    appId: '1:30188463436:ios:fe1c68aae7ca2741179be9',
    messagingSenderId: '30188463436',
    projectId: 'social-media-platform-34794',
    storageBucket: 'social-media-platform-34794.firebasestorage.app',
    androidClientId: '30188463436-9q44hre5h3ooods0erikpbkdqe446rjl.apps.googleusercontent.com',
    iosClientId: '30188463436-apk9rrf186g5i1bf1jdij9pjosup2n3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX2m1EwU7GRLakXed3Kg_CmQvLWLuGZQ4',
    appId: '1:30188463436:web:8fc9383f58e58945179be9',
    messagingSenderId: '30188463436',
    projectId: 'social-media-platform-34794',
    authDomain: 'social-media-platform-34794.firebaseapp.com',
    storageBucket: 'social-media-platform-34794.firebasestorage.app',
    measurementId: 'G-5C6VMV0MBN',
  );
}
